// Imports
import mongoose from 'mongoose';
import Sensor from './model/Sensor.js';
import Tph from './model/Tph.js';
import GpsNmea from './model/GpsNmea.js';
import RainCounter from './model/RainCounter.js';
import nmea from 'node-nmea';
import fs from 'fs';

// Path to the data
const sensors = '/dev/shm/sensors';
const tphLog = '/dev/shm/tph.log';
const rainCounterLog = '/dev/shm/rainCounter.log';
const gpsNmea = '/dev/shm/gpsNmea';

watchMyFile(sensors);
watchMyFile(tphLog);
watchMyFile(gpsNmea);
watchMyFile(rainCounterLog);


// ------------------------- functions -------------------------//
function watchMyFile(filePath) {

    /* Watches a given file if it changed or not */

    let myJSON;

    console.log(`Watching for file changes on ${filePath}`);

    fs.watchFile(filePath, (curr, prev) => {

        console.log(`${filePath} file Changed`);

        console.log("Read file");
        fs.readFile(filePath, 'utf-8', (err, data) => {
            if (err) {
                return console.error(err);
            }
            myJSON = saveData(data, filePath);

        })
        saveData
    })


}

async function saveData(data, filePath) {
    /* Saving in the database the data */

    // connect to mongoDB
    mongoose.connect('mongodb://localhost:27017/test');

    let dataJSON;
    let myNewData;

    if (filePath.includes("sensors")) {

        dataJSON = changeToJSON(data);
        myNewData = createSensor(dataJSON);

    }
    if (filePath.includes("tph")) {

        dataJSON = changeToJSON(data);
        myNewData = createTph(dataJSON);

    }

    if (filePath.includes("gpsNmea")) {
        myNewData = createGPSNmea(data);
    }

    if (filePath.includes("rainCounter")) {
        myNewData = createRainCounter(data);
    }

    // insert in mongo database
    await myNewData.save();

}

function changeToJSON(data) {
    /* Change data to a JSON */
    return JSON.parse(data.toString());
}

function createSensor(dataJson) {
    /* Create Instance of Sensor: simulated data */
    return new Sensor({
        time: dataJson.date,
        temp: dataJson.measure[0].value,
        pre: dataJson.measure[1].value,
        hum: dataJson.measure[2].value,
        lum: dataJson.measure[3].value,
        wind_dir: dataJson.measure[4].value,
        wind_speed: dataJson.measure[5].value,
        wind_speed_max: dataJson.measure[6].value,
    });
}

function createTph(dataJson) {
    /* Create instance of data generated by the Raspberry */
    return new Tph({
        time: dataJson.date,
        temp: dataJson.temp,
        hum: dataJson.hygro,
        pre: dataJson.press
    });
}

function createGPSNmea(data) {
    /* Create instance for GPS data */
    const val = data.toString().split("$");
    const gprmc = '$' + val[2].slice(0, -1);
    const value = nmea.parse(gprmc);

    return new GpsNmea({
        lat: value.loc.geojson.coordinates[0],
        long: value.loc.geojson.coordinates[1]
    });
}

function createRainCounter(data) {
    /* Create instance for rain data */
    const val = data.toString();
    return new RainCounter({
        time: val
    });
}

